#action.yml

name: "DM Alert Action"
inputs:
  repo:
    description: "the pr repo name"
    required: true
  pr_number:
    description: "the pr number"
    required: true
  branch_name:
    description: "the pr branch name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      run: pip install requests
      shell: bash
      
    #https://shipyard.build/blog/your-first-python-github-action/
    - name: setup env  
      run: |
        echo "INPUT_REPO=${{ github.event.inputs.repo }}" >> $GITHUB_ENV
        echo "INPUT_PR_NUMBER=${{ github.event.inputs.pr_number }}" >> $GITHUB_ENV
        echo "INPUT_BRANCH_NAME=${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV
      shell: bash
      
    - name: run dependencies update notifier script
      id: run-python
      run: python ./DMAlertMain.py
      shell: bash
