#action.yml

name: "DM Alert Action"
inputs:
  repo:
    description: "the pr repo name"
    required: true
  pr_number:
    description: "the pr number"
    required: true
  branch_name:
    description: "the pr branch name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      run: pip install requests
    - name: run python
      id: run-python
      run: python ./DMAlertMain.py
